server:
  port: 9191

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 2 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:5001/eureka/
    healthcheck:
      enabled: true  

  
  
spring:
  application:
    name: db-op-service  
     
mes:
  datasource:
    details: v7bxfgW6hd4qrs7C3nY7MhvnPPvugM7dJrzzb5hUpxUEP0K3eqdWOzAag5B+e4FW
    
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true   
      
resilience4j:
  circuitbreaker:
    instances:
      createProductCB:
        failure-rate-threshold: 100
        sliding-window-size: 10
        sliding-window-type: count-based
        minimum-number-of-calls: 2
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 4
        wait-duration-in-open-state: 1000
      
      getProductCB:
        failure-rate-threshold: 100
        sliding-window-size: 10
        sliding-window-type: count-based
        minimum-number-of-calls: 2
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 4
        wait-duration-in-open-state: 1000
      
      updateProductCB:
        failure-rate-threshold: 100
        sliding-window-size: 10
        sliding-window-type: count-based
        minimum-number-of-calls: 2
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 4
        wait-duration-in-open-state: 1000   
      
      deleteProductCB:
        failure-rate-threshold: 100
        sliding-window-size: 10
        sliding-window-type: count-based
        minimum-number-of-calls: 2
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 4
        wait-duration-in-open-state: 1000  
